# Generated by Django 4.2.16 on 2024-10-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
